[2025-01-11T08:41:36.443+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.ft_balance_f scheduled__2025-01-10T00:00:00+00:00 [queued]>
[2025-01-11T08:41:36.456+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.ft_balance_f scheduled__2025-01-10T00:00:00+00:00 [queued]>
[2025-01-11T08:41:36.457+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-11T08:41:36.689+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ft_balance_f> on 2025-01-10 00:00:00+00:00
[2025-01-11T08:41:36.698+0000] {standard_task_runner.py:60} INFO - Started process 135 to run task
[2025-01-11T08:41:36.702+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'ft_balance_f', 'scheduled__2025-01-10T00:00:00+00:00', '--job-id', '559', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpxruo6v5e']
[2025-01-11T08:41:36.706+0000] {standard_task_runner.py:88} INFO - Job 559: Subtask ft_balance_f
[2025-01-11T08:42:44.675+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.ft_balance_f scheduled__2025-01-10T00:00:00+00:00 [running]> on host 403e7aadd7ee
[2025-01-11T08:42:44.826+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='agushchin' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='ft_balance_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-10T00:00:00+00:00'
[2025-01-11T08:42:44.856+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-11T08:42:44.933+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-11T08:42:44.946+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=ft_balance_f, execution_date=20250110T000000, start_date=20250111T084136, end_date=20250111T084244
[2025-01-11T08:42:45.004+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-11T08:42:45.037+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
