[2025-01-11T09:22:49.410+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2025-01-11T09:22:35.231531+00:00 [queued]>
[2025-01-11T09:22:49.421+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2025-01-11T09:22:35.231531+00:00 [queued]>
[2025-01-11T09:22:49.422+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-11T09:22:49.674+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ft_balance_f> on 2025-01-11 09:22:35.231531+00:00
[2025-01-11T09:22:49.683+0000] {standard_task_runner.py:60} INFO - Started process 172 to run task
[2025-01-11T09:22:49.687+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'ft_balance_f', 'manual__2025-01-11T09:22:35.231531+00:00', '--job-id', '602', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpjegx1f41']
[2025-01-11T09:22:49.691+0000] {standard_task_runner.py:88} INFO - Job 602: Subtask ft_balance_f
[2025-01-11T09:22:49.752+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.ft_balance_f manual__2025-01-11T09:22:35.231531+00:00 [running]> on host 403e7aadd7ee
[2025-01-11T09:22:49.847+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='agushchin' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='ft_balance_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T09:22:35.231531+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-11T09:22:35.231531+00:00'
[2025-01-11T09:22:49.867+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-11T09:22:49.918+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-11T09:22:49.928+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=ft_balance_f, execution_date=20250111T092235, start_date=20250111T092249, end_date=20250111T092249
[2025-01-11T09:22:49.980+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-11T09:22:50.018+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
