[2024-12-30T17:47:13.132+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.ft_balance_f scheduled__2024-12-29T00:00:00+00:00 [queued]>
[2024-12-30T17:47:13.154+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.ft_balance_f scheduled__2024-12-29T00:00:00+00:00 [queued]>
[2024-12-30T17:47:13.155+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2024-12-30T17:47:13.208+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ft_balance_f> on 2024-12-29 00:00:00+00:00
[2024-12-30T17:47:13.223+0000] {standard_task_runner.py:60} INFO - Started process 435 to run task
[2024-12-30T17:47:13.229+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'ft_balance_f', 'scheduled__2024-12-29T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpo3z8pr_j']
[2024-12-30T17:47:13.236+0000] {standard_task_runner.py:88} INFO - Job 32: Subtask ft_balance_f
[2024-12-30T17:47:13.984+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.ft_balance_f scheduled__2024-12-29T00:00:00+00:00 [running]> on host 403e7aadd7ee
[2024-12-30T17:47:14.100+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='agushchin' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='ft_balance_f' AIRFLOW_CTX_EXECUTION_DATE='2024-12-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-29T00:00:00+00:00'
[2024-12-30T17:47:14.120+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2024-12-30T17:47:14.175+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-12-30T17:47:14.191+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=ft_balance_f, execution_date=20241229T000000, start_date=20241230T174713, end_date=20241230T174714
[2024-12-30T17:47:14.253+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-30T17:47:15.102+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
