[2025-01-11T09:22:49.434+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.md_account_d manual__2025-01-11T09:22:35.231531+00:00 [queued]>
[2025-01-11T09:22:49.448+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.md_account_d manual__2025-01-11T09:22:35.231531+00:00 [queued]>
[2025-01-11T09:22:49.449+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-11T09:22:49.708+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): md_account_d> on 2025-01-11 09:22:35.231531+00:00
[2025-01-11T09:22:49.718+0000] {standard_task_runner.py:60} INFO - Started process 176 to run task
[2025-01-11T09:22:49.723+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'md_account_d', 'manual__2025-01-11T09:22:35.231531+00:00', '--job-id', '604', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmph09tjlqx']
[2025-01-11T09:22:49.726+0000] {standard_task_runner.py:88} INFO - Job 604: Subtask md_account_d
[2025-01-11T09:22:49.795+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.md_account_d manual__2025-01-11T09:22:35.231531+00:00 [running]> on host 403e7aadd7ee
[2025-01-11T09:22:49.881+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='agushchin' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='md_account_d' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T09:22:35.231531+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-11T09:22:35.231531+00:00'
[2025-01-11T09:22:49.901+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-11T09:22:49.950+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-11T09:22:49.959+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=md_account_d, execution_date=20250111T092235, start_date=20250111T092249, end_date=20250111T092249
[2025-01-11T09:22:50.015+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-11T09:22:50.059+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
