[2025-01-04T08:09:45.614+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.call_clear_all_data scheduled__2025-01-03T00:00:00+00:00 [queued]>
[2025-01-04T08:09:45.625+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.call_clear_all_data scheduled__2025-01-03T00:00:00+00:00 [queued]>
[2025-01-04T08:09:45.626+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-04T08:09:46.035+0000] {taskinstance.py:2191} INFO - Executing <Task(SQLExecuteQueryOperator): call_clear_all_data> on 2025-01-03 00:00:00+00:00
[2025-01-04T08:09:46.048+0000] {standard_task_runner.py:60} INFO - Started process 84 to run task
[2025-01-04T08:09:46.053+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'call_clear_all_data', 'scheduled__2025-01-03T00:00:00+00:00', '--job-id', '307', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmp99ob_olv']
[2025-01-04T08:09:46.057+0000] {standard_task_runner.py:88} INFO - Job 307: Subtask call_clear_all_data
[2025-01-04T08:09:46.126+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.call_clear_all_data scheduled__2025-01-03T00:00:00+00:00 [running]> on host 403e7aadd7ee
[2025-01-04T08:09:46.273+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='agushchin' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='call_clear_all_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-03T00:00:00+00:00'
[2025-01-04T08:09:46.276+0000] {sql.py:276} INFO - Executing: CALL stage.clear_all_data()
[2025-01-04T08:09:46.286+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-04T08:09:46.296+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-04T08:09:46.310+0000] {sql.py:450} INFO - Running statement: CALL stage.clear_all_data(), parameters: None
[2025-01-04T08:09:46.344+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=call_clear_all_data, execution_date=20250103T000000, start_date=20250104T080945, end_date=20250104T080946
[2025-01-04T08:09:46.387+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-04T08:09:46.427+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
