[2025-01-11T08:41:36.442+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.ft_posting_f scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-01-11T08:41:36.456+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.ft_posting_f scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-01-11T08:41:36.457+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-11T08:41:36.691+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ft_posting_f> on 2025-01-06 00:00:00+00:00
[2025-01-11T08:41:36.700+0000] {standard_task_runner.py:60} INFO - Started process 136 to run task
[2025-01-11T08:41:36.703+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'ft_posting_f', 'scheduled__2025-01-06T00:00:00+00:00', '--job-id', '558', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmppn3sm6qk']
[2025-01-11T08:41:36.706+0000] {standard_task_runner.py:88} INFO - Job 558: Subtask ft_posting_f
[2025-01-11T08:42:44.658+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.ft_posting_f scheduled__2025-01-06T00:00:00+00:00 [running]> on host 403e7aadd7ee
[2025-01-11T08:42:44.838+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='agushchin' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='ft_posting_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-06T00:00:00+00:00'
[2025-01-11T08:42:44.881+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-11T08:42:58.838+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-11T08:42:58.849+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=ft_posting_f, execution_date=20250106T000000, start_date=20250111T084136, end_date=20250111T084258
[2025-01-11T08:42:58.911+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-11T08:42:58.945+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
