[2025-01-06T07:38:34.372+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.md_account_d scheduled__2025-01-05T00:00:00+00:00 [queued]>
[2025-01-06T07:38:34.384+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.md_account_d scheduled__2025-01-05T00:00:00+00:00 [queued]>
[2025-01-06T07:38:34.384+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-01-06T07:38:34.689+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): md_account_d> on 2025-01-05 00:00:00+00:00
[2025-01-06T07:38:34.697+0000] {standard_task_runner.py:60} INFO - Started process 204 to run task
[2025-01-06T07:38:34.700+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'md_account_d', 'scheduled__2025-01-05T00:00:00+00:00', '--job-id', '427', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpee8bk3z8']
[2025-01-06T07:38:34.703+0000] {standard_task_runner.py:88} INFO - Job 427: Subtask md_account_d
[2025-01-06T07:38:34.759+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.md_account_d scheduled__2025-01-05T00:00:00+00:00 [running]> on host 403e7aadd7ee
[2025-01-06T07:38:35.846+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='agushchin' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='md_account_d' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-05T00:00:00+00:00'
[2025-01-06T07:38:37.885+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-06T07:38:38.901+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-06T07:38:40.900+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=md_account_d, execution_date=20250105T000000, start_date=20250106T073834, end_date=20250106T073840
[2025-01-06T07:38:41.924+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-06T07:38:41.950+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
