[2025-01-03T07:50:15.448+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.call_clear_all_data manual__2025-01-03T07:50:04.005061+00:00 [queued]>
[2025-01-03T07:50:15.457+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.call_clear_all_data manual__2025-01-03T07:50:04.005061+00:00 [queued]>
[2025-01-03T07:50:15.458+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-03T07:50:15.626+0000] {taskinstance.py:2191} INFO - Executing <Task(SQLExecuteQueryOperator): call_clear_all_data> on 2025-01-03 07:50:04.005061+00:00
[2025-01-03T07:50:15.636+0000] {standard_task_runner.py:60} INFO - Started process 85 to run task
[2025-01-03T07:50:15.639+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'call_clear_all_data', 'manual__2025-01-03T07:50:04.005061+00:00', '--job-id', '289', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpkzpo9_nc']
[2025-01-03T07:50:15.641+0000] {standard_task_runner.py:88} INFO - Job 289: Subtask call_clear_all_data
[2025-01-03T07:50:15.692+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.call_clear_all_data manual__2025-01-03T07:50:04.005061+00:00 [running]> on host 403e7aadd7ee
[2025-01-03T07:50:15.796+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='agushchin' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='call_clear_all_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-03T07:50:04.005061+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-03T07:50:04.005061+00:00'
[2025-01-03T07:50:15.797+0000] {sql.py:276} INFO - Executing: CALL stage.clear_all_data()
[2025-01-03T07:50:15.806+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-03T07:50:15.816+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-03T07:50:15.828+0000] {sql.py:450} INFO - Running statement: CALL stage.clear_all_data(), parameters: None
[2025-01-03T07:50:15.848+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=call_clear_all_data, execution_date=20250103T075004, start_date=20250103T075015, end_date=20250103T075015
[2025-01-03T07:50:15.892+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-03T07:50:15.924+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
